site_name: splinter
site_url: https://supabase.github.io/splinter
site_description: Supabase Project Linter

repo_name: supabase/splinter
repo_url: https://github.com/supabase/splinter

nav:
    - Welcome: 'index.md'
    - Lints:
      - Unindexed Foreign Keys: '0001_unindexed_foreign_keys.md'
      - Auth Users Exposed: '0002_auth_users_exposed.md'
      - Auth RLS InitPlan: '0003_auth_rls_initplan.md'
      - No Primary Key: '0004_no_primary_key.md'
      - Unused Index: '0005_unused_index.md'
      - Multiple Permissive Policies: '0006_multiple_permissive_policies.md'

theme:
    name: 'material'
    features:
      - navigation.expand
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase.github.io/splinter
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
