version: '3'
services:

  db:
    container_name: supabase-db
    build:
        context: ..
        dockerfile: ./dockerfiles/Dockerfile
        args:
          PG_VERSION: ${SUPABASE_VERSION:-15.1.1.13}
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - ./bin/installcheck
