version: '3'
services:

  test:
    container_name: repo_test
    build:
        context: ..
        dockerfile: ./dockerfiles/Dockerfile
        args:
          PG_VERSION: ${SUPABASE_VERSION:-15.1.1.13}
    command:
      - ./bin/installcheck
