name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ['3.11']
            postgres-version: ['14', '15']
    services:

      postgres:
        image: supabase/postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
        - 5610:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install --with=dev

    - name: Test
      run: |
        poetry run pytest
